### ISSUE TITLE
Error discovering purifier after updating to v.10

### ISSUE THREAD

**Issue by mynnx** [iprak/winix#30]
Hi!  My Winix entity is unavailable after updating to the most recent version.  I see this in the logs; is this a known issue?

I'm slightly out-of-date with HA (2021.6.6), but can update if necessary.

```
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 10:01:47 PM (2 occurrences)
Last logged: 10:01:47 PM

Exception in discovery_platform_listener when dispatching 'discovery.platform_discovered_load_platform.fan': ({'service': 'load_platform.fan', 'platform': 'winix', 'discovered': {}},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 120, in discovery_platform_listener await task File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 140, in component_platform_discovered await self.async_setup_platform(platform, {}, info) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 229, in async_setup_platform platform = await async_prepare_setup_platform( File "/usr/src/homeassistant/homeassistant/setup.py", line 328, in async_prepare_setup_platform platform = integration.get_platform(domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}") File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1014, in _gcd_import File "<frozen importlib._bootstrap>", line 991, in _find_and_load File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 671, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 783, in exec_module File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/config/custom_components/winix/fan.py", line 117, in <module> class WinixPurifier(FanEntity): File "/config/custom_components/winix/fan.py", line 134, in WinixPurifier def extra_state_attributes(self) -> Union[Mapping[str, Any], None]: TypeError: 'ABCMeta' object is not subscriptable
Exception in discovery_platform_listener when dispatching 'discovery.platform_discovered_load_platform.sensor': ({'service': 'load_platform.sensor', 'platform': 'winix', 'discovered': {}},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 120, in discovery_platform_listener await task File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 140, in component_platform_discovered await self.async_setup_platform(platform, {}, info) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 229, in async_setup_platform platform = await async_prepare_setup_platform( File "/usr/src/homeassistant/homeassistant/setup.py", line 328, in async_prepare_setup_platform platform = integration.get_platform(domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}") File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1014, in _gcd_import File "<frozen importlib._bootstrap>", line 991, in _find_and_load File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 671, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 783, in exec_module File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/config/custom_components/winix/sensor.py", line 36, in <module> class WinixSensor(Entity): File "/config/custom_components/winix/sensor.py", line 53, in WinixSensor def extra_state_attributes(self) -> Union[Mapping[str, Any], None]: TypeError: 'ABCMeta' object is not subscriptable
```

**Comment by iprak** [comment]
I pushed out another release with some fixes, please give that a try.

**Comment by mynnx** [comment]
v.11 worked like a charm - thanks very much for the fix!
