### ISSUE TITLE
Error when adding the integration

### ISSUE THREAD

**Issue by nasdim** [iprak/winix#74]
After successfully copying the files from the repository's `custom_components/winix` directory to the `<config directory>/custom_components/winix/` in my homeassistant's directory, I get the following error when trying to add the integration. Below I have also posted the log:

![Screenshot 2024-09-04 at 11 34 45 AM](https://github.com/user-attachments/assets/fee69f99-ee31-42e3-bf52-563ec5ed43c1)

`2024-09-04 15:32:56.396 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.winix.config_flow
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 836, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 853, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
f"Error while performing RPC get_device_info_list ({result_code}): {
^
SyntaxError: unterminated string literal (detected at line 139)
2024-09-04 15:32:56.409 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration winix: Exception importing custom_components.winix.config_flow`

**Comment by nasdim** [comment]
Updated log:

`2024-09-04 15:46:19.839 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.winix
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
2024-09-04 15:46:19.847 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration winix: Unable to import component: Exception importing custom_components.winix
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
ImportError: Exception importing custom_components.winix
2024-09-04 15:46:51.227 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.winix.application_credentials
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
2024-09-04 15:46:52.679 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.winix
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
ImportError: Exception importing custom_components.winix
2024-09-04 15:47:04.790 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.winix.application_credentials
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
2024-09-04 15:47:05.840 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.winix
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
ImportError: Exception importing custom_components.winix
2024-09-04 15:47:18.612 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.winix.config_flow
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
2024-09-04 15:47:18.623 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration winix: Exception importing custom_components.winix.config_flow
2024-09-04 15:47:21.081 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.winix.application_credentials
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
2024-09-04 15:47:21.857 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.winix
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
File "/config/custom_components/winix/__init__.py", line 30, in <module>
from .helpers import Helpers, WinixException
File "/config/custom_components/winix/helpers.py", line 139
ImportError: Exception importing custom_components.winix`

**Comment by iprak** [comment]
What is your HomeAssistant version?

**Comment by nasdim** [comment]
> What is your HomeAssistant version?

Core
2023.11.2
Frontend
20231030.2

**Comment by nasdim** [comment]
I updated my version to the latest and the problem is now resolved. Thank you @iprak! Great custom component!
