### ISSUE TITLE
Error setting up entry Winix Purifier

### ISSUE THREAD

**Issue by LimitedLombax** [iprak/winix#79]
Hey having some issues setting up this integration. I'm using HACS to download the files needed from the repo. I am getting this error log when logging in:

Logger: homeassistant.config_entries
Source: config_entries.py:551
First occurred: 6:37:59 PM (2 occurrences)
Last logged: 7:02:43 PM

Error setting up entry Winix Purifier for winix
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1232, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/winix/fan.py", line 103, in <module>
    class WinixPurifier(WinixEntity, FanEntity):
  File "/config/custom_components/winix/fan.py", line 110, in WinixPurifier
    | FanEntityFeature.TURN_ON
      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'FanEntityFeature' has no attribute 'TURN_ON'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/winix/__init__.py", line 131, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, SUPPORTED_PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1860, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1145, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1145, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1133, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1060, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1252, in _load_platform
    raise ImportError(
ImportError: Exception importing custom_components.winix.fan

**Comment by iprak** [comment]
Your HomeAssistant is probably less than 2024.8.0, please update.
https://developers.home-assistant.io/blog/2024/07/19/fan-fanentityfeatures-turn-on_off/

**Comment by LimitedLombax** [comment]
That was it. Thanks!
