### ISSUE TITLE
Winix component does not load on HA 2024.10.3

### ISSUE THREAD

**Issue by andyrak** [iprak/winix#82]
After upgrading to HA 2024.10.3, the Winix component no longer loads within HA.

Here are the corresponding logs:

```
2024-10-23 21:56:29.419 DEBUG (MainThread) [custom_components.winix.helpers] Obtaining device list
2024-10-23 21:56:29.709 INFO (MainThread) [custom_components.winix.manager] No purifiers found
2024-10-23 21:56:29.709 INFO (MainThread) [custom_components.winix.manager] Updating devices
2024-10-23 21:56:29.709 ERROR (MainThread) [custom_components.winix.manager] Unexpected error fetching WinixManager data
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/winix/manager.py", line 89, in _async_update_data
await self.async_update()
File "/config/custom_components/winix/manager.py", line 120, in async_update
for device_wrapper in self._device_wrappers:
TypeError: 'NoneType' object is not iterable
```

The same error occurs if I delete the device and try to re-add/re-auth.

Please let me know if there is any more information I can provide.

**Comment by andyrak** [comment]
My apologies, it looks as though Winix's native app, if not accessed for a year, will automatically de-register any devices within your account.

The error message in this case completely makes sense. Will close the issue; hope this comes in handy for anyone in the future who runs into this.

**Comment by iprak** [comment]
Thanks for the investigation. I can put a check there so that we don't get `NoneType` error. Yes the Winix library would probably not load any devices in that case.
