### ISSUE TITLE
Winix integration failing after reboot

### ISSUE THREAD

**Issue by jum0n** [iprak/winix#84]
Restarted HA this morning (had not noticed that there were any issues, but didnt check all integrations) and Winix refuses to start now.  I've manually reloaded and its continuing to try.  Perhaps its due to something unavailable on Winix site, but just wanted to post this here to get a head start on any possible issues with HA updates.

Getting the following message when it fails to load:
Unexpected error fetching WinixManager data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/winix/manager.py", line 89, in _async_update_data
    await self.async_update()
  File "/config/custom_components/winix/manager.py", line 120, in async_update
    for device_wrapper in self._device_wrappers:
TypeError: 'NoneType' object is not iterable

**Comment by iprak** [comment]
What is your version?

**Comment by edalquist** [comment]
Seeing the same thing on HA 2024.11.1 & Winix 1.1.8

**Comment by jum0n** [comment]
> What is your version?

Core 2024.11.1
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.2
Winix 1.1.8

**Comment by iprak** [comment]
That exception indicates that we did not get device list from Winix. An error handling can be added but  there still won't be any devices. I have restarted a few times I tool 2024.11.1 but have not encountered this.

**Comment by kmfd55** [comment]
Same error also.

**Comment by iprak** [comment]
There is a fix to better handle the exception in 1.1.9. This does not address missing data from Winix end. You can reload the integration to see if new is being provided.

**Comment by iprak** [comment]
Enabling Debug mode on the integration might also show more relevant information.

**Comment by edalquist** [comment]
Full log:

```
2024-11-10 08:33:21.864 DEBUG (MainThread) [custom_components.winix.helpers] Obtaining device list
2024-11-10 08:33:22.171 INFO (MainThread) [custom_components.winix.manager] No purifiers found
2024-11-10 08:33:22.172 INFO (MainThread) [custom_components.winix.manager] Updating devices
2024-11-10 08:33:22.172 ERROR (MainThread) [custom_components.winix.manager] Unexpected error fetching WinixManager data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/winix/manager.py", line 89, in _async_update_data
    await self.async_update()
  File "/config/custom_components/winix/manager.py", line 120, in async_update
    for device_wrapper in self._device_wrappers:
TypeError: 'NoneType' object is not iterable
2024-11-10 08:33:22.178 DEBUG (MainThread) [custom_components.winix.manager] Finished fetching WinixManager data in 0.006 seconds (success: False)
```

**Comment by edalquist** [comment]
I'm not able to re-registered my C545s with the app either, seems like something is broken on the Winix end.

**Comment by sdoowo200leldls** [comment]
Same issue here. My air purifier was removed from the Winix app and trying to re-register it resulted in these messages:

![Screenshot_20241110-114522~2](https://github.com/user-attachments/assets/678f902b-8719-436d-a3ff-690c5e889a14)
![Screenshot_20241110-114450~2](https://github.com/user-attachments/assets/7c63e8b4-a806-4b16-9b3e-a3893892e79a)

**Comment by iprak** [comment]
You might want to post an issue on the app in App store. That might get their attention.

**Comment by schmitzcj** [comment]
Updating to v1.1.9, re-registering my C545's, and restarting HA solved the issue for me.

For other experiencing device registration issues, I would agree with @iprak about contacting Winix. I am not sure how useful this will be for others, but the app prompted me to update my C545's to firmware v1.3.0.

**Comment by sdoowo200leldls** [comment]
> Updating to v1.1.9, re-registering my C545's, and restarting HA solved the issue for me.
> 
> For other experiencing device registration issues, I would agree with @iprak about contacting Winix. I am not sure how useful this will be for others, but the app prompted me to update my C545's to firmware v1.3.0.

What did you update to v1.1.9?

**Comment by schmitzcj** [comment]
> What did you update to v1.1.9?

My apologies for the confusion. I was referring to the HA Winix integration which was released a few posts above, [v1.1.9](https://github.com/iprak/winix/releases/tag/v1.1.9). Even after updating to v1.1.9, I received an error from the integration because Winix (the company) had de-registered my devices.

**Comment by sdoowo200leldls** [comment]
Thanks for clarifying. I was able to successfully get my air purifier back in the app by adding it to a different wifi ssid.

**Comment by jum0n** [comment]
Updated to 1.1.9 and then had to add all my air purifiers back into the Winix app before available again.  Thanks!

**Comment by schmitzcj** [comment]
>I wonder what caused the purge? Was it because we never logged into the Winix app since everything was being controlled via Home Assistant? Or was it excessive API calls or something like that?

I would also like to think that it may have been a result of infrequent app usage, but I distinctly remember opening the app late-September during a filter change.

> I did not encounter this problem at all and I do take the HomeAssistant updates as soon as they are released. I wonder if this was due to Winix inactivity from HomeAssistant end? I have automations which daily turn two purifiers on and off.

I updated my Home Assistant to 2024.11.2 the day it was released and also have automations that toggle my purifier settings daily. I did not have any issue during re-registering like others have mentioned (switching networks, needing to use a new device).

**Comment by uhTWO** [comment]
> > I wonder what caused the purge? Was it because we never logged into the Winix app since everything was being controlled via Home Assistant? Or was it excessive API calls or something like that?
> 
> I would also like to think that it may have been a result of infrequent app usage, but I distinctly remember opening the app late-September during a filter change.
> 
> > I did not encounter this problem at all and I do take the HomeAssistant updates as soon as they are released. I wonder if this was due to Winix inactivity from HomeAssistant end? I have automations which daily turn two purifiers on and off.
> 
> I updated my Home Assistant to 2024.11.2 the day it was released and also have automations that toggle my purifier settings daily. I did not have any issue during re-registering like others have mentioned (switching networks, needing to use a new device).

If I had to guess, they had a catastrophic loss of data and blamed it on "inactivity". I know for sure I had logged in recently, and WHY would you require your customers to manually log into an app that is designed to AUTOMATE the functions of your product? That doesn't make ANY sense at all.

**Comment by PalmDynasty** [comment]
Just happened to me yesterday. My place had a power outage and when it came back online, Winix refused to authenticate.

Home Assistant pops up saying that I need repair the Winix integration. It asks for my Winix account password but gives "Invalid credentials" when I enter it.

I logged into the app on my phone and it wouldn't accept my password either, had to reset it. I'm now able to log in on the app and control my air purifier, but Home Assistant still won't authenticate. Nothing was de-registered like that one guy above, so this might be something else?

When I try to add a new entry in the Winix integration, it asks for a username/password. Gives the same "Invalid credentials". If I type the wrong username it says "Invalid User", so it looks like it is connecting to the Winix servers.
